from python:3.8

ENV AIRFLOW_VERSION=2.2.2
ENV PYTHON_VERSION=3.8
CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-2.2.2/constraints-3.8.txt"
RUN pip install "apache-airflow==2.2.2" --constraint "3.8"
