apiVersion: batch/v1
kind: Job
metadata:
  name: python-hello-world
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
      - name: python-hello-world
        image: python:3.7
        command: ["python",  "-c", "print('Hello World')"]
      restartPolicy: Never
  backoffLimit: 4