apiVersion: batch/v1
kind: Job
metadata:
  name: data-copier
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: data-copier
        image: dgadiraju/data-copier:latest
        command: ["data_copier", "departments,categories"]
      imagePullSecrets:
      - name: dockerhubcred
      restartPolicy: Never
  backoffLimit: 4