apiVersion: batch/v1
kind: Job
metadata:
  name: data-copier
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: data-copier
        image: dgadiraju/data-copier:latest
        command: ["data_copier", "departments,categories"]
        env:
        - name: "BASE_DIR"
          value: "/retail_db_json"
        - name: "DB_HOST"
          value: "172.17.0.3"
        - name: "DB_PORT"
          value: "5432"
        - name: "DB_NAME"
          value: "retail_db"
        - name: "DB_USER"
          value: "retail_user"
        - name: "DB_PASS"
          value: "itversity"
        volumeMounts:
        - name: retail-db-json
          mountPath: /retail_db_json
      volumes:
      - name: retail-db-json
        hostPath:
          path: /retail_db_json
      imagePullSecrets:
      - name: dockerhubcred
      restartPolicy: Never
  backoffLimit: 4